apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.app.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.app.name }}
spec:
  selector:
    matchLabels:
        app: {{ $.Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ $.Values.app.name }}
          image: {{ $.Values.app.image }}:{{ $.Values.app.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.app.port }}
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: {{ $.Values.app.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: {{ $.Values.app.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.app.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ $.Values.app.port }}
  selector:
    app: {{ $.Values.app.name }}
