name: Docker CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_NAME: registry.eecc.info/eecc/co2-calculator-coppa

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.eecc.info -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Image
        run: docker build -t $IMAGE_NAME:dev .

  push-dev:
    name: Push Dev Image (main branch)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.eecc.info -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push dev tag
        run: docker push $IMAGE_NAME:dev

  push-versioned:
    name: Push Versioned Tags
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.eecc.info -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag & Push version + latest
        run: |
          TAG=${GITHUB_REF##*/}
          docker tag $IMAGE_NAME:dev $IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:dev $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: push-dev
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_PROD }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Rollout Restart
        run: |
          kubectl --namespace co2-calculator-coppa rollout restart deploy co2-calculator-coppa
