name: Docker CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_NAME: registry.eecc.info/eecc/co2-calculator-coppa

jobs:
  full:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Start VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn.conf
          sudo openvpn --config vpn.conf --daemon
          sleep 10
      
      - name: Generate Docker config from base64 string
        run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"registry.eecc.info\":{\"auth\":\"${{ secrets.DOCKER_AUTH_STRING }}\"}}}" > ~/.docker/config.json
          chmod 600 ~/.docker/config.json

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:dev ./docker

      - name: Push dev image (if main branch)
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE_NAME:dev

      - name: Push version + latest (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=${GITHUB_REF##*/}
          docker tag $IMAGE_NAME:dev $IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:dev $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

      # - name: Set up kubeconfig
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      #     chmod 600 ~/.kube/config

      # - name: Deploy to Kubernetes
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     kubectl --namespace co2-calculator-coppa rollout restart deploy co2-calculator-coppa
